CREATE DATABASE db_01 DEFAULT CHARACTER SET utf8 DEFAULT  COLLATE utf8_general_ci;

use db_01;

CREATE TABLE student (
	id VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
    birthday DATE NOT NULL
);

ALTER TABLE student ADD age int NOT NULL;
ALTER TABLE student MODIFY age VARCHAR(10) NOT NULL;
ALTER TABLE student DROP COLUMN age;

DROP TABLE student;